# Generated by Django 6.0 on 2025-12-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0003_signup_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='created_at',
        ),
    ]
