# Generated by Django 6.0 on 2025-12-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0005_alter_signup_email_alter_signup_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='crop_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mobile',
            field=models.CharField(max_length=60),
        ),
    ]
