# Generated by Django 6.0 on 2025-12-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0006_cropsale_alter_signup_email_alter_signup_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropsale',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
