# Generated by Django 6.0 on 2025-12-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0007_cropsale_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropsale',
            name='image',
            field=models.ImageField(upload_to='pending_crops/'),
        ),
    ]
