# Generated by Django 6.0 on 2025-12-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0008_alter_cropsale_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropsale',
            name='image',
            field=models.ImageField(upload_to='static/crop_img'),
        ),
    ]
