# Generated by Django 6.0 on 2025-12-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0009_alter_cropsale_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropsale',
            name='image',
            field=models.ImageField(upload_to='crop_img/'),
        ),
    ]
