# Generated by Django 6.0 on 2025-12-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0011_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_img/'),
        ),
        migrations.AlterField(
            model_name='cropsale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_img/'),
        ),
    ]
