# Generated by Django 6.0 on 2025-12-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0012_ad_image_alter_cropsale_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
