# Generated by Django 6.0 on 2025-12-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0023_remove_order_cart_remove_order_payment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropsale',
            name='crop',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cropsale',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
