# Generated by Django 6.0 on 2025-12-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0026_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='placed', max_length=20),
        ),
    ]
