# Generated by Django 6.0 on 2025-12-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0027_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='placed', max_length=20),
        ),
    ]
