# Generated by Django 6.0 on 2026-01-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0029_order_cancel_requested_at_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
