# Generated by Django 5.2.10 on 2026-01-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0036_alter_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='image',
            field=models.ImageField(default='userimages/default.png', upload_to='userimages/'),
        ),
    ]
