# Generated by Django 5.2.10 on 2026-01-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0037_signup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.ImageField(upload_to='userimages/'),
        ),
    ]
