# Generated by Django 5.2.10 on 2026-01-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0039_alter_signup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.ImageField(default='media/userimages/default.png', upload_to='userimages/'),
        ),
    ]
