"""
Django settings for ikhedut_portal project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "unsafe-dev-key")


# SECURITY WARNING: don't run with debug turned on in production!

# DEBUG = True

DEBUG = os.environ.get("DEBUG", "False") == "True"

 

# ALLOWED_HOSTS = []
# SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# ALLOWED_HOSTS = [
#     "ikhedut-portal.onrender.com",
#     "localhost",
#     "127.0.0.1",
# ]

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    # 'unfold',
    "rest_framework", 
    'ikhedut',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'ikhedut_portal.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "ikhedut_portal" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ALLOWED_HOSTS = ["*"]
 
WSGI_APPLICATION = 'ikhedut_portal.wsgi.application'


DATABASES = {
    "default": dj_database_url.parse(
        os.environ.get("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
        ssl_require=not DEBUG
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = '/static/'

# Where collectstatic puts files (production)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Where your source static files live (development)
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ------------- this is only for django admin panel UI change --------------------

JAZZMIN_SETTINGS = {
    "site_title": "Admin Panel",
    "site_header": "My Project",    
    "site_brand": "Ikhedut Portal",
    "welcome_sign": "Welcome to Ikhedut Portal",
    "show_sidebar": True,
    "navigation_expanded": False,
    "copyright": "Ikhedut Portal",
    "icons": {
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
    },
    "site_logo": "img/header.png",
    "site_icon": "img/favicon.png",
    # for login image
    "custom_css": "css/admin_custom.css",
}

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ]
}
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
